### PR TITLE
feat: add system tray menu items

### PR DESCRIPTION
**Pull request by ledongthuc**
Mar-05-2023 17-37-10

### CODE REVIEW

**Review by huytd — APPROVED** [review]

**Comment by huy-qn** [comment]
hmm, why don't I see this in the latest build?

**Comment by ledongthuc** [comment]
I have a quick build bundle locally on the main branch, and the features are still available.
So I guess the commit that @huytd used to build doesn't have it.

**Comment by huy-qn** [comment]
> I have a quick build bundle locally on the main branch, and the features are still available. So I guess the commit that @huytd used to build doesn't have it.

I cloned the main branch and build manually though, I can see your commits included in the code.

**Comment by huy-qn** [comment]
Silly me, I just had too many apps in the menu bar so the icon of Goxkey doesn't have room to show.

**Pull request merged**
